[phases.setup]
nixPkgs = ["nodejs-20_x"]

[phases.install]
cmds = [
  "cd backend && npm install --legacy-peer-deps",
  "cd backend && npm run build",
  "cd backend && npx prisma generate"
]

[start]
cmd = "cd backend && npm start"
